apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-reply3
spec:
  provider:
    vault:
      server: "https://vault.platform.replycontrol.com/"
      path: "reply3"
      version: v2
      auth:
        tokenSecretRef:
          name: "vault-token-global"
          key: "token"
          namespace: external-secrets