apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service1
spec:
  refreshInterval: "3s"
  secretStoreRef:
    name: vault-backend-reply3
    kind: ClusterSecretStore
  target:
    name: service1
  data:
  - secretKey: env
    remoteRef:
      key: services/prod/service1
      property: env
