apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-role-get-update-binding
subjects:
  - kind: ServiceAccount
    name: secret-get-update
    namespace: external-secrets
roleRef:
  kind: Role
  name: secret-access-role-get-update
  apiGroup: rbac.authorization.k8s.io
